In [1]:
import numpy as np

Некоторые свойства numpy:

1ая часть
np.reshape(x,y) - меняет размер матрицы
np.shape() - размер матрицы

np.arange(x, dtype=) - создает одномерный массив длиной x
np.fill(x) - заполняет массив одинаковыми числами
np.transpose() - транспонирует матрицу
np.flatten() - многомерный массив в одномерный
np.concatenate((a, b, c)) - конкантенация массивов array([1., 2., 3., 4., 5., 6., 7., 8., 9.])
np.concatenate((a,b), axis=0) - можно соединять по осям
np[:,np.newaxis] - добавление новой оси

Часть 2:

np.zeros_like(a) - заполняет уже созданный массив "a" - нулями
np.ones_like(a) - аналогично - единицами
np.identity(x, dtype=float) - создает диагональную матрицу x на x
np.eye(x, k=1, dtype=float) - создает k-диагональ из единиц в диагональной 
np.sqrt(a) и другие функции abs, sign, sqrt, log, log10, exp, sin, cos, tan, arcsin, arccos, arctan, sinh, cosh, tanh, arcsinh, arccosh, и arctanh
np.pi
np.e
a.sum() - суммирование всех элементов = np.sum(a)
a.prod() - произведение всех элементов = np.prod(a)
a.mean() - среднее арифметическое
a.var() - вариация
a.std() - девиация
a.min() - минимум
a.max() - максимум
a.argmin() - возвращает индекс минимального значения (можно по оси искать)
a.argmax() - возвращает индекс максимального значения   min(max(x, minval), maxval) 
a.sort() - сортировка
a.clip(0, 5) - значения в массиве могут быть «сокращенны», чтобы принадлежать заданному диапазону.
np.unique(a) - Уникальные элементы могут быть извлечены вот та
a.diagonal() - для двухмерных массивов диагональ можно получить так

Часть 3:
any(c)/all(c)Операторы any и all могут быть использованы для определения истинны ли хотя бы один или все элементы соответственно
np.logical_and(a > 0, a < 3)
np.logical_not(b)
np.logical_or(b, c)
where(boolarray, truearray, falsearray): - функция where создает новый массив из двух других массивов одинаковых длин используя булев фильтр для выбора межу двумя элементами
np.isnan(a) - проверка на Nan
np.isfinite(a) - проверка на конечность
a[a >= 6] - выбор элементов в массиве a, который подходит под условие внутири (проходит по каждому элементу)
!мы передаем булев массив a>=6 как индекс для операции доступа по индексу массива a, возвращаемый массив будет хранить только True значения
a.take(b) - Специальная функция take доступна для выполнения выборки с целочисленными массивами
a.put([0, 3], b) - будет брать значения из исходного массива и записывать их на специфические индексы в другом put-массиве

np.dot(a, b) - возвращает скалярное произведение векторов, перемножает матрицы 
A @ B @ C - перемножение матриц
np.linalg.det(a) - определитель матрицы
vals, vecs = np.linalg.eig(a) - собственный вектор и собственное значение матрицы
b = np.linalg.inv(a) - невырожденная матрица
np.dot(a, b) - диагональная

Часть 4:
Полиндромы:
np.poly() Передавая список корней, можно получить коэффициенты уравнения
np.roots([1, 4, -2, 3]) - нахождение корней у многочлена
np.polyint([1, 1, 1, 1]) - нахождение коэффициентов первообразной у многочлена
np.polyder([1./4., 1./3., 1./2., 1., 0.]) - производная
polyadd, polysub, polymul и polydiv также поддерживают суммирование, вычитание, умножение и деление коэффициентов многочлена
polyval() подставляет в многочлен заданное значение
polyfit может быть использована для подбора (интерполяции) многочлена заданного порядка к набору значений
Статистика:
np.median(a) - медиана 
np.corrcoef(a) - Коэффициент корреляции для некоторых переменных, наблюдается несколько раз и может быть найден из массивов вида: [[x1, x2, ...], [y1, y2, ...], [z1, z2, ...], ...], где x, y, z это разные квантовые наблюдаемые и номера указывают количество «наблюдений
np.cov(a) - Имеем возвращаемый массив c[i, j] который хранит корреляционный коэффициент для i-тых и j-тых квантовых наблюдаемых.
Случайные ряды:
np.random.seed(293423)
randint(min, max) Для генерации случайного целочисленного числа в диапазоне [min, max)         определяют рамки   для красоты]
Для генерации нескольких значений используем аргумент size
np.random.shuffle(l) - случайный образом перемешивает массив l

Математические операции:


In [2]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)

a + b

array([6., 4., 9.])

In [3]:
a - b

array([-4.,  0., -3.])

In [4]:
a * b


array([ 5.,  4., 18.])

In [5]:
b / a

array([5., 1., 2.])

In [6]:
a % b

array([1., 0., 3.])

In [7]:
b**a

array([  5.,   4., 216.])

 Происходит поэлементное произведение

In [8]:
a = np.array([[1,2], [3,4]], float)
b = np.array([[2,0], [1,3]], float)
a * b

array([[ 2.,  0.],
       [ 3., 12.]])

In [10]:
a = np.zeros((2,2), float)
b = np.array([-1., 3.], float)

Автоматически добавляет оси

In [11]:
a + b

array([[-1.,  3.],
       [-1.,  3.]])

In [12]:
a + b[np.newaxis,:]

array([[-1.,  3.],
       [-1.,  3.]])

In [13]:
a + b[:,np.newaxis]

array([[-1., -1.],
       [ 3.,  3.]])

In [14]:
a = np.array([6, 2, 5, -1, 0], float)
a.clip(0, 5)

array([5., 2., 5., 0., 0.])

In [15]:
np.unique(a)

array([-1.,  0.,  2.,  5.,  6.])

Операторы сравнения

In [16]:
a = np.array([1, 3, 0], float)
b = np.array([0, 3, 2], float)
a > b

array([ True, False, False])

In [17]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [18]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [19]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)

array([ True,  True,  True])

In [20]:
a = np.array([1, 3, 0], float)
np.where(a != 0, 1 / a, a)

C:\h\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([1.        , 0.33333333, 0.        ])

In [21]:
np.where(a > 0, 3, 2)

array([3, 3, 2])

In [22]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [23]:
np.isfinite(a)

array([ True, False, False])

In [24]:
a = np.array([[6, 4], [5, 9]], float)
a >= 6

array([[ True, False],
       [False,  True]])

In [25]:
a[a >= 6]

array([6., 9.])

In [26]:
a[np.logical_and(a > 5, a < 9)]

array([6.])

In [27]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a[b]

array([2., 2., 4., 8., 6., 4.])

In [28]:
a.take(b)

array([2., 2., 4., 8., 6., 4.])

В следующем примере мы берем индексы элемента:

In [29]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

In [ ]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([0, 0, 1], int)
a.take(b, axis=0)

In [ ]:
a.take(b, axis=1)

In [1]:
a = np.array([0, 1, 2, 3, 4, 5], float)
b = np.array([9, 8, 7], float)
a.put([0, 3], b)
a

NameError: name 'np' is not defined

In [ ]:
a = np.array([0, 1, 2, 3, 4, 5], float)
a.put([0, 3], 5)
a

In [ ]:
a = np.array(range(12))
b = a.reshape(3,4)
b

In [ ]:
b[:, 1] = 2
b

In [ ]:
b[1,:] = 3
b

Математика многочленов

In [30]:
np.poly([-1, 1, 1, 10])

array([  1., -11.,   9.,  11., -10.])

In [31]:
np.roots([1, 4, -2, 3])

array([-4.5797401 +0.j        ,  0.28987005+0.75566815j,
        0.28987005-0.75566815j])

Многолчен вида: x^3 + 4x^2 - 2x + 3 имеет такие коэффициенты

In [32]:
np.polyint([1, 1, 1, 1])

array([0.25      , 0.33333333, 0.5       , 1.        , 0.        ])

Получается такое x^4/4 + x^3/3 + x^2/2 + x + C
И от него берем производную:

In [ ]:
np.polyder([1./4., 1./3., 1./2., 1., 0.])

В многочлен вида x^3 - 2x^2 + 2 подставляем точку x = 4

In [ ]:
np.polyval([1, -2, 0, 2], 4)

In [ ]:
x = [1, 2, 3, 4, 5, 6, 7, 8]
y = [0, 2, 1, 3, 7, 10, 11, 19]
np.polyfit(x, y, 2)

In [ ]:
a = np.array([[1, 2, 1, 3], [5, 3, 1, 8]], float)
c = np.corrcoef(a)
c


In [ ]:
np.random.seed(293423)

In [ ]:
np.random.rand(5)

In [ ]:
np.random.rand(2,3)

In [ ]:
np.random.randint(5, 10)

In [ ]:
np.random.normal(size=5)

In [ ]:
l = np.arange(10)
np.random.shuffle(l)
l