In [98]:
import numpy as np
import math
from sklearn import preprocessing

In [4]:
def result_mark(weights, marks):
    return round((weights * marks).sum())
    

In [12]:
weights = np.array([0.3, 0.42, 0.14, 0.14])
marks = np.array([9, 10, 8, 6])
result_mark(weights, marks)

9.0

In [19]:
def change_array(array, number):
    array[::3] = number
    return array

In [20]:
array = np.array([3, 5, 1, 0, -3, 22, 213436])
number = -111
change_array(array, number)

array([-111,    5,    1, -111,   -3,   22, -111])

In [73]:
def find_close(array1, array2, precision):
    #a = np.abs(array1 - array2) < precision
    a = np.where(np.abs(array1 - array2) < precision)
    #c = np.arange(array1.size) 
    return a[0]

In [75]:
array1 = np.array([1.5, 0.5, 2, -4.1, -3, 6, -1])
array2 = np.array([1.2, 0.5, 1, -4, 3, 0, -1.2])
precision = 0.5
type(find_close(array1, array2, precision))

numpy.ndarray

In [107]:
def block_matrix(block):
    a = np.vstack((block, block))
    return np.hstack((a,a))

In [108]:
block = np.array([[0, 1, 2], [3, 4, 5]])
block_matrix(block)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [109]:
def diag_prod(matrix):
    dig = matrix.diagonal() 
    return (dig[dig != 0]).prod()

In [110]:
matrix = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
diag_prod(matrix)

32

In [112]:
np.polyint([4, 6, 0, 1], m = 1, k = 5)

array([1., 2., 0., 1., 5.])

In [113]:
def antiderivative(coefs):
    return np.polyint(coefs, k = 5)

In [114]:
coefs = np.array([4, 6, 0, 1])
antiderivative(coefs)

array([1., 2., 0., 1., 5.])

In [158]:
matrix = np.array([[1, 2, 3, 4], [0, 5, 6, 7], [0, 0, 8, 9], [0, 0, 0, 10]])
matrix

array([[ 1,  2,  3,  4],
       [ 0,  5,  6,  7],
       [ 0,  0,  8,  9],
       [ 0,  0,  0, 10]])

In [204]:
def make_symmetric(matrix):
    tr_matrix = matrix.T
    i, j = np.indices(tr_matrix.shape)
    return matrix + tr_matrix - np.diag(tr_matrix[i == j]) 

In [205]:
matrix = np.array([[1, 2, 3, 4], [0, 5, 6, 7], [0, 0, 8, 9], [0, 0, 0, 10]])
make_symmetric(matrix)

array([[ 1,  2,  3,  4],
       [ 2,  5,  6,  7],
       [ 3,  6,  8,  9],
       [ 4,  7,  9, 10]])

In [287]:
matrix[i == j]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 4

In [234]:
def construct_matrix(m, a, b):
    return np.arange(a, b + 1) * np.ones((m, b - a + 1))

In [238]:
m = 5
a = 3
b = 10
construct_matrix(m, a, b)

array([[ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [250]:
def cosine_similarity(vec1, vec2):
    numerator = (vec1 * vec2).sum()
    den1 = np.sqrt((vec1 ** 2).sum())
    
    den2 = np.sqrt((vec2 ** 2).sum())
    return numerator/ (den1 * den2)

In [251]:
vec1 = np.array([-2, 1, 0, -5, 4, 3, -3])
vec2 = np.array([0, 2, -2, 10, 6, 0, 0])
cosine_similarity(vec1, vec2)

-0.25

In [113]:
def normalizel(matrix):
    std = matrix.std(axis = 0)
    k = (matrix - matrix.mean(axis = 0))/matrix.std(axis = 0)
    k[k != k] = 0
    return k

In [116]:
matrix = np.array([[0, 4, 4200], [0, 10, 5000], [0, 2, 1000]])
normalizel(matrix)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([[ 0.        , -0.39223227,  0.46291005],
       [ 0.        ,  1.37281295,  0.9258201 ],
       [ 0.        , -0.98058068, -1.38873015]])

In [108]:
def n(X):    
    nom = (X-X.min(axis=0))
    denom = X.max(axis=0) - X.min(axis=0)
    denom[denom==0] = 1
    return nom/denom

In [109]:
matrix = np.array([[1, 4, 4200], [0, 10, 5000], [1, 2, 1000]])

normalized_X = preprocessing.normalize(matrix, axis = 0)
normalized_X



array([[0.70710678, 0.36514837, 0.63578008],
       [0.        , 0.91287093, 0.75688105],
       [0.70710678, 0.18257419, 0.15137621]])

In [110]:
n(matrix)

array([[1.  , 0.25, 0.8 ],
       [0.  , 1.  , 1.  ],
       [1.  , 0.  , 0.  ]])

In [106]:
matrix = np.array([[1, 4, 4200], [0, 10, 5000], [1, 2, 1000]])

normalized_X = preprocessing.normalize(matrix, axis = 0, norm = 'l2')
normalized_X

array([[0.70710678, 0.36514837, 0.63578008],
       [0.        , 0.91287093, 0.75688105],
       [0.70710678, 0.18257419, 0.15137621]])